// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA18uVw1AS-CqgCaDhYOFkgFJRK4NF53m4',
    appId: '1:87893363102:web:b40fff06d8a4ef76f72e8f',
    messagingSenderId: '87893363102',
    projectId: 'money-c6605',
    authDomain: 'money-c6605.firebaseapp.com',
    storageBucket: 'money-c6605.firebasestorage.app',
    measurementId: 'G-DSJD057EM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_CpE2yA59nx8CnsuuHUPVWgQYVPmI7Zc',
    appId: '1:87893363102:android:0626a0eb19041e7ff72e8f',
    messagingSenderId: '87893363102',
    projectId: 'money-c6605',
    storageBucket: 'money-c6605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSO5NUXhJdCGc0Mo37XSssJmg9PxSyBWc',
    appId: '1:87893363102:ios:1f197603806af0c1f72e8f',
    messagingSenderId: '87893363102',
    projectId: 'money-c6605',
    storageBucket: 'money-c6605.firebasestorage.app',
    iosBundleId: 'com.example.moneyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSO5NUXhJdCGc0Mo37XSssJmg9PxSyBWc',
    appId: '1:87893363102:ios:1f197603806af0c1f72e8f',
    messagingSenderId: '87893363102',
    projectId: 'money-c6605',
    storageBucket: 'money-c6605.firebasestorage.app',
    iosBundleId: 'com.example.moneyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA18uVw1AS-CqgCaDhYOFkgFJRK4NF53m4',
    appId: '1:87893363102:web:146be19e8296fea4f72e8f',
    messagingSenderId: '87893363102',
    projectId: 'money-c6605',
    authDomain: 'money-c6605.firebaseapp.com',
    storageBucket: 'money-c6605.firebasestorage.app',
    measurementId: 'G-2RMN9K4DFE',
  );
}
